backend/controllers/CoursesController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Courses;
use backend\models\CoursesSearch;
use backend\models\SearchCourseQuestionType;
use backend\models\CourseKeywordSearch;
use backend\models\UserCourseSearch;
use backend\models\QuestionSearch;
use backend\models\CourseGroupSearch;
use yii\web\Controller;
use yii\helpers\FileHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;


/**
 * CoursesController implements the CRUD actions for Courses model.
 */
class CoursesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Courses models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CoursesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
      // action examples

    public function actionUpload()
    {
        $model = new Courses();
        $post =Yii::$app->request->post();
        $model->load(Yii::$app->request->post());
        $imageFile = $_FILES["Courses"];
        $directory = Yii::getAlias('@backend/web/img/temp') . DIRECTORY_SEPARATOR . Yii::$app->session->id . DIRECTORY_SEPARATOR;
        //return var_dump($directory);
        if (!is_dir($directory)) {
            FileHelper::createDirectory($directory);
        }
        if ($imageFile) {
            $uid = uniqid(time(), true);
            $fileName = $imageFile["name"]["image"];
            $filePath = $directory . $fileName;
            copy($imageFile["tmp_name"]["image"], $filePath);            

            $path = '../img/temp/' . $fileName;
            return Json::encode([
                'files' => [
                    [
                        'name' => $fileName,
                        'size' => $imageFile["size"]["image"],
                        'url' => $path,
                        'thumbnailUrl' => $path,
                        'deleteUrl' => 'image-delete?name=' . $fileName,
                        'deleteType' => 'POST',
                    ],
                ],
            ]);
            
        }

        return '';
    }
    

    /**
     * Displays a single Courses model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($tag=null, $id)
    {
        $searchQuestionTypeModel = new SearchCourseQuestionType();
        $searchQuestionTypeModel->course_id = $id;
        $questionTypeDataProvider = $searchQuestionTypeModel->search(Yii::$app->request->queryParams);
        
        $searchKeywordModel = new CourseKeywordSearch();
        $searchKeywordModel->course_id = $id;
        $courseKeywordDataProvider = $searchKeywordModel->search(Yii::$app->request->queryParams);
        
        $searchQuestionModel= new QuestionSearch();
        $searchQuestionModel->course_id = $id;
        $dataQuestionProvider= $searchQuestionModel->search(Yii::$app->request->queryParams);
        
        $searchCourseUserModel= new UserCourseSearch();
        $searchCourseUserModel->course_id = $id;
        $CourseUserProvider= $searchCourseUserModel->search(Yii::$app->request->queryParams);

        $searchCourseGroupModel= new CourseGroupSearch();
        $searchCourseGroupModel->course_id = $id;
        $CourseGroupProvider= $searchCourseGroupModel->search(Yii::$app->request->queryParams);        

        return $this->render('view', [
            'model' => $this->findModel($id),
            'tag' => $tag,
            'searchQuestionTypeModel' => $searchQuestionTypeModel,
            'questionTypeDataProvider' => $questionTypeDataProvider,
            'searchKeywordModel' => $searchKeywordModel,
            'courseKeywordDataProvider' => $courseKeywordDataProvider,
            'dataQuestionProvider' => $dataQuestionProvider,
            'searchQuestionModel' => $searchQuestionModel,
            'CourseUserProvider' => $CourseUserProvider,
            'searchCourseUserModel' => $searchCourseUserModel,
            'CourseGroupProvider' => $CourseGroupProvider,
            'searchCourseGroupModel' => $searchCourseGroupModel,            
        ]);
    }

    /**
     * Creates a new Courses model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Courses();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            yii::$app->utility->moveCourseImage($model);
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    /**
     * Updates an existing Courses model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $image_text = $model->image;
        if ($model->load(Yii::$app->request->post()))
        {   
            if (is_null($model->image)||$model->image == ""){
                $model->image = $image_text;
            }   
            if ( $model->save()) {          
                yii::$app->utility->moveCourseImage($model);
                $model->save();
                return $this->redirect(['view', 'id' => $model->id]);
            } 
        }else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Courses model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Courses model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Courses the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Courses::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/courses/_form.php
<?php

use backend\models\Coursestatuslookup;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\jui\DatePicker;
use yii\widgets\ActiveForm;
use mihaildev\ckeditor\CKEditor;
use dosamigos\fileupload\FileUpload;
use dosamigos\fileupload\FileUploadUI;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model backend\models\Courses */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="courses-form">

     <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

   <!--div class="field-course_image">
       <label for="course-image" class="control-label">Course_image</label>
       <!?= FileUploadUI::widget([
        'model' => $model,
        'attribute' => 'image',
        'url' => ['courses/upload', 'id' => $model->id],
        'gallery' => false,
        'fieldOptions' => [
            'accept' => 'image/*'
        ],
        'clientOptions' => [
            'maxFileSize' => 6000000
        ],
        // ...
        'clientEvents' => [
            'fileuploaddone' => 'function(e, data) {         
                                    console.log(data.jqXHR.responseJSON.files[0].url);
                                    console.log( $(\'input[type="hidden"][name="Courses[image]"]\'));
                                    $(\'input[type="hidden"][name="Courses[image]"]\').val(data.jqXHR.responseJSON.files[0].url);
                                    console.log($(\'input[type="hidden"][name="Courses[image]"]\').val());
                                }',
            'fileuploadfail' => 'function(e, data) {
                                }',
            'fileuploaddrop' => 'function(e, data) {
                                $(\'input[type="hidden"][name="Course[image]"]\').val("");
                                }',               
        ],
    ]); ?>
    </div-->
    <?= $form->field($model, 'status')->dropDownList(
        ArrayHelper::map(Coursestatuslookup::find()->all(), "id", "name"),
        ["prompt"=>"Select Status"]
    ) ?>
    <?= $form->field($model, 'duration')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/courses/_formDetail.php
<?php

use backend\models\Courses;
use backend\models\Coursestatuslookup;
use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\models\QuestionType;
use backend\models\Question;
use backend\models\CourseKeyword;
use yii\bootstrap\Tabs;
?>
<br>
<div class="courses-view">


    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'price',
            'description:ntext',
            'image',
            'created_at',
            'percent',
            [
                'label'  => 'Status',
                'value'  => call_user_func(function ($data) {
                    $status = $data->status;
                    $typeObject = Coursestatuslookup::find()->where(['id'=>$status])->One();
                    if ($typeObject) {
                        return $typeObject->name;
                    }
                    return $status;
                }, $model)
            ],
            'duration',
        ],
    ]) ?>

</div>

backend/views/courses/_formGroup.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CourseGroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Course Groups';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-group-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Course Group', ['course-group/create','course_id' => $model->id], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $CourseGroupProvider,
        'filterModel' => $searchCourseGroupModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'name',
            'course_id',
            ['class' => 'yii\grid\ActionColumn',
            'buttons' => [
                'additional_icon' => function ($url, $modelRow, $key) {
                    return Html::a ('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> ', ['course-group/delete'], [
                            'data'=>[
                                'method' => 'post',
                                'params'=>[
                                    'id' => $modelRow->id,
                                ],
                            ]
                        ]);
                },
                'update' => function ($url, $modelRow, $key) {
                    return Html::a ('<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> ', ['group-user/create','group_id'=>$modelRow->id]);
                }, 
                'view'=>function ($url, $modelRow) {
                            $t = Yii::getAlias('@web').'/group-user/index?group_id='.$modelRow->id;
                            return Html::button('<span class="glyphicon glyphicon-eye-open"></span>', ['value'=>($t), 'class' => 'btn btn-default btn-xs custom_button']);
                        },                
            ],
            'template' => '{update} {view} {additional_icon}'


        ],
        ],
    ]); ?>
    <div id="group-user">
    </div>
</div>

backend/views/courses/_formQuestion.php
<?php

use backend\models\Courses;
use backend\models\Coursestatuslookup;
use backend\models\Keyword;
use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\models\QuestionType;
use backend\models\Question;
use backend\models\CourseKeyword;
use yii\bootstrap\Tabs;
use yii\grid\GridView;
?>
<br>

<div class="question-index">
    <p>
        <?= Html::a('Create Question', ['question/create','tag'=>'course','course_id'=>$model->id], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataQuestionProvider,
        'filterModel' => $searchQuestionModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'course_id',
                'value' => function ($data) {
                    $course_id = $data->course_id;
                    $course = Courses::find()->where(['id'=>$course_id])->One();
                    if ($course) {
                        return $course->name . '(' . $course_id . ')';
                    }
                    return $course_id;
                },
            ],
            [
                'attribute' => 'type',
                'value' => function ($data) {
                    $type = $data->type;
                    $questionType = QuestionType::find()->where(['id'=>$type])->One();
                    if ($questionType) {
                        return $questionType->type . '(' . $type . ')';
                    }
                    return $type;
                },
            ],
            [
                'attribute' => 'keyword',
                'value' => function ($data) {
                    $keywordId = $data->keyword;
                    $keyword = Keyword::find()->where(['id'=>$keywordId])->One();
                    if ($keyword) {
                        return $keyword->name . '(' . $keywordId . ')';
                    }
                    return $keywordId;
                },
            ],
             ['attribute' => 'question_text',
             'label' =>'question_text',
                'value' => function ($model) {
                    return yii::$app->utility->textCut($model->question_text, 100);
                },           
             'contentOptions' => ['style' => 'width:300px; white-space: normal;'],
            ],
            ['attribute' => 'question_audio',
                'label' =>'question_audio',
                'value' => function ($model) {
                    return yii::$app->utility->textCut($model->question_audio, 20);
                },
                'contentOptions' => ['style' => 'max-width:300px; white-space: normal;'],
            ],              
            ['attribute' => 'question_img',
                'label' =>'question_img',
                'value' => function ($model) {
                    return yii::$app->utility->textCut($model->question_img, 20);
                },                
                 'contentOptions' => ['style' => 'max-width:300px; white-space: normal;'],
            ],  
            // 'question_img:ntext',
            // 'question_video:ntext',
            // 'answer_text:ntext',
            // 'answer_img:ntext',
            // 'hint:ntext',
            // 'description:ntext',
            // 'time',

            ['class' => 'yii\grid\ActionColumn',
                'template' => '{updated} {deleted}',
                'buttons' => [
                    'deleted' => function ($url, $model) use ($course_id) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['question/delete','id'=>$model->id,'tag'=>"course",'course_id'=>$course_id],[
                            'title'=>'delete',
                            'class' => '',
                            'data' => [
                                'confirm' => 'Bạn có chắc chắn muốn xóa question.',
                                'method' => 'post',
                            ]]);
                    },
                    'updated' => function ($url, $model) use ($course_id) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['question/update','id'=>$model->id,'tag'=>"course",'course_id'=>$course_id],[
                            'title'=>'update',
                            'class' => '',
                            'data' => [
                                'method' => 'post',
                            ]]);
                    }
                ],],
        ],
    ]); ?>
</div>

backend/views/courses/_formQuestionType.php
<?php

use backend\models\Courses;
use backend\models\Coursestatuslookup;
use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\models\QuestionType;
use backend\models\Question;
use backend\models\CourseKeyword;
use yii\bootstrap\Tabs;
use yii\grid\GridView;
?>
<br>
<div class="courses-index">

    <p>
        <?= Html::a('Create Question Type For Course', ['course-question-type/create','tag'=>'question_type','course_id' => $model->id], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $questionTypeDataProvider,
        'filterModel' => $searchQuestionTypeModel,
        'columns' => [
             ['class' => 'yii\grid\SerialColumn'],
            'id',
            [
                'attribute' => 'question_type_id',
                'value' => function ($data) {
                    $question_type_id = $data->question_type_id;
                    $typeObject= QuestionType::find()->where(['id'=>$question_type_id])->One();
                    if ($typeObject) {
                        return $typeObject->type . '(' . $question_type_id . ')';
                    }
                    return $question_type_id;
                },
            ],
            [
                'attribute' => 'question_type_id',
                'label' => 'Question Type Name',
                'value' => function ($data) {
                    $question_type_id = $data->question_type_id;
                    $typeObject= QuestionType::find()->where(['id'=>$question_type_id])->One();
                    if ($typeObject) {
                        return $typeObject->type_name;
                    }
                    return $question_type_id;
                },
            ],
            'priority',
            ['class' => 'yii\grid\ActionColumn',
                'template' => '{updated} {deleted}',
                'buttons' => [
                    'deleted' => function ($url, $model) use ($course_id) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['course-question-type/delete','id'=>$model->id,'tag'=>"course",'course_id'=>$course_id],[
                            'title'=>'delete',
                            'class' => '',
                            'data' => [
                                'confirm' => 'Bạn có chắc muốn xóa question type.',
                                'method' => 'post',
                            ]]);
                    },
                    'updated' => function ($url, $model) use ($course_id) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['course-question-type/update','id'=>$model->id,'tag'=>"course",'course_id'=>$course_id],[
                            'title'=>'update',
                            'class' => '',
                            'data' => [
                                'method' => 'post',
                            ]]);
                    }
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/courses/_formUser.php
<?php

use backend\models\Courses;
use backend\models\Coursestatuslookup;
use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\models\QuestionType;
use backend\models\Question;
use backend\models\CourseKeyword;
use yii\bootstrap\Tabs;
use yii\grid\GridView;
?>
<br>
<div class="courses-index">

    <?= GridView::widget([
        'dataProvider' => $CourseUserProvider,
        //'filterModel' => $searchCourseUserModel,
        'columns' => [
             ['class' => 'yii\grid\SerialColumn'],
              'user.username',
              'start_date',
              'duration',
                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{view}{updated} {deleted}',
                    'buttons' => [
                        'view' => function ($url, $model) use ($course_id) {
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['user/view','id'=>$model->user_id],[
                                'title'=>'view user',
                                'class' => '',
                                'data' => [
                                    'method' => 'post',
                                ]]);
                        },
                        'deleted' => function ($url, $model) use ($course_id) {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['user-course/delete','id'=>$model->id,'tag'=>"course",'course_id'=>$course_id],[
                                'title'=>'delete',
                                'class' => '',
                                'data' => [
                                    'confirm' => 'Bạn có chắc muốn xóa user này khỏi khóa học.',
                                    'method' => 'post',
                                ]]);
                        },
                        'updated' => function ($url, $model) use ($course_id) {
                            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['user-course/update','id'=>$model->id,'tag'=>"course",'course_id'=>$course_id],[
                                'title'=>'update',
                                'class' => '',
                                'data' => [
                                    'method' => 'post',
                                ]]);
                        }
                    ],
                ],
            
        ],
    ]); ?>
</div>

backend/views/courses/_formkeyword.php
<?php

use backend\models\Courses;
use backend\models\Coursestatuslookup;
use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\models\QuestionType;
use backend\models\Question;
use backend\models\CourseKeyword;
use yii\bootstrap\Tabs;
use yii\grid\GridView;
?>
<br>
<div class="courses-index">

    <p>
        <?= Html::a('Create Keyword For Course', ['course-keyword/create', 'tag'=>'course' , 'course_id' => $model->id], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $courseKeywordDataProvider,
        'filterModel' => $searchKeywordModel,
        'columns' => [
             ['class' => 'yii\grid\SerialColumn'],
            'id',
            'keyword:ntext',
            'priority',
            ['class' => 'yii\grid\ActionColumn',
                'template' => '{updated} {deleted}',
                'buttons' => [
                    'deleted' => function ($url, $model) use ($course_id) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['course-keyword/delete','id'=>$model->id,'tag'=>"course",'course_id'=>$course_id],[
                            'title'=>'delete',
                            'class' => '',
                            'data' => [
                                'confirm' => 'Bạn có chắc muốn xóa keyword.',
                                'method' => 'post',
                            ]]);
                    },
                    'updated' => function ($url, $model) use ($course_id) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['course-keyword/update','id'=>$model->id,'tag'=>"course",'course_id'=>$course_id],[
                            'title'=>'update',
                            'class' => '',
                            'data' => [
                                'method' => 'post',
                            ]]);
                    }
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/courses/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\CoursesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="courses-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'price') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'percent') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/courses/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Courses */

$this->title = 'Create Courses';
$this->params['breadcrumbs'][] = ['label' => 'Courses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="courses-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/courses/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\CoursesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Courses';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="courses-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Courses', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'price',
            'description:ntext',
           /*[
                'attribute' => 'image',
                'format' => 'html',    
                'value' => function ($data) {
                    return Html::img("/esl/". $data['image'],
                        ['width' => '70px']);
                },
            ],*/
            // 'created_at',
            // 'percent',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/courses/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Courses */

$this->title = 'Update Courses: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Courses', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="courses-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>