backend/models/GroupUser.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "group_user".
 *
 * @property integer $id
 * @property integer $group_id
 * @property integer $user_id
 */
class GroupUser extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'group_user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['group_id', 'user_id'], 'required'],
            [['group_id', 'user_id'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'group_id' => 'Group ID',
            'user_id' => 'User ID',
        ];
    }
}

backend/controllers/GroupUserController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\GroupUser;
use backend\models\CourseGroup;
use backend\models\Courses;
use backend\models\User;
use backend\models\GroupUserSearch;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GroupUserController implements the CRUD actions for GroupUser model.
 */
class GroupUserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all GroupUser models.
     * @return mixed
     */
    public function actionIndex($group_id)
    {
        $searchModel = new GroupUserSearch();
        //$query = GroupUser::find();
        $query = new Query;
        $query->select(['group_user.id', 'group_user.group_id', 'user.username as user_id']) 
        ->from('group_user')
        ->leftJoin('user', 'user.id = group_user.user_id');

        $group = CourseGroup::findOne($group_id);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        // grid filtering conditions
        $query->andFilterWhere([
            'group_id' => $group_id,
        ]);
        $this->layout = false;
        return $this->render('index', [
            "course_id" => $group->course_id,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single GroupUser model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new GroupUser model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($group_id = '')
    {
        $model = new GroupUser();
        $model->group_id = $group_id;        
        $group = CourseGroup::findOne($group_id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $course = Courses::findOne($group->course_id);
            return $this->redirect(['courses/view', 'id' => $group->course_id, 'tag' => 'course_group']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'group_id' => $group_id,
                'course_id' => $group->course_id,
            ]);
        }
    }

    /**
     * Updates an existing GroupUser model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing GroupUser model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete()
    {
        $request = Yii::$app->request;
        $id = $request->post('id');
        
        $group_user = $this->findModel($id);
        $group = CourseGroup::findOne($group_user->group_id);
        
        $group_user->delete();
        return $this->redirect(['courses/view', 'id' => $group->course_id, "tag" => "course_group"]);
    }

    /**
     * Finds the GroupUser model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return GroupUser the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = GroupUser::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/group-user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\models\User;
use yii\helpers\ArrayHelper;
use yii\db\Query;
/* @var $this yii\web\View */
/* @var $model app\models\GroupUser */
/* @var $form yii\widgets\ActiveForm */
?>
<?php

$userQuery = (new Query())->select('user_id')->from('user_course')->where(['course_id' => $course_id]);
$groupQuery = (new Query())->select('group_id')->from('course_group')->where(['course_id' => $course_id]);
$userExQuery = (new Query())->select('user_id')->from('group_user')->where(['group_id' => $groupQuery]);
$userRegQuery = (new Query())->select('user_id')->from('user_course')->where(['course_id' => $course_id]);
$userSearch = User::find()
->andWhere([ 'id' => $userQuery])
->andWhere([ 'not in', 'id', $userExQuery])
->all();
?>
<div class="group-user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'group_id')->textInput() ?>

    <?= $form->field($model, 'user_id')->dropDownList(
        ArrayHelper::map($userSearch, "id", "username"),
        ["prompt"=>"Select User"]
    ) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/group-user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\GroupUserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="group-user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'group_id') ?>

    <?= $form->field($model, 'user_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/group-user/create.php
<?php

use yii\helpers\Html;
use yii\db\Query;


/* @var $this yii\web\View */
/* @var $model app\models\GroupUser */

$this->title = 'Create Group User';
$this->params['breadcrumbs'][] = ['label' => 'Group Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'course_id' => $course_id
    ]) ?>

</div>

backend/views/group-user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GroupUserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>
<div class="group-user-index">

   <p><h2>
        Danh sách học sinh của nhóm
        </h2>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'group_id',
            'user_id',

            ['class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'additional_icon' => function ($url, $modelRow, $key) {
                        return Html::a ('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> ', ['group-user/delete'], [
                                'data'=>[
                                    'method' => 'post',
                                    'params'=>[
                                        'id' => $modelRow["id"],
                                    ],
                                ]
                            ]);
                    },              
                ],
                'template' => '{view} {additional_icon}'

            ],
        ],
    ]); ?>
</div>

backend/views/group-user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\GroupUser */

$this->title = 'Update Group User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Group Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="group-user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/group-user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\GroupUser */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Group Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'group_id',
            'user_id',
        ],
    ]) ?>

</div>